package com.example.spring.app.book.domain;
// Generated Dec 27, 2016 4:46:31 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name = "categories", catalog = "ezgo")
public class Category implements java.io.Serializable {

    private int id;
    private String name;
    private String description;
    private boolean isParent;

    public Category() {
    }

    public Category(int id, String name, String description, boolean isParent) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.isParent = isParent;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description", nullable = false)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "isParent", nullable = false)
    public boolean isIsParent() {
        return this.isParent;
    }

    public void setIsParent(boolean isParent) {
        this.isParent = isParent;
    }

}
