package com.example.spring.app.book.domain;
// Generated Dec 27, 2016 4:46:31 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.util.Date;

/**
 * Comments generated by hbm2java
 */
@Entity
@Table(name = "comments", catalog = "ezgo")
public class Review implements java.io.Serializable {

    private String id;
    private String owner;
    private String content;
    private boolean deleted;
    private String eventId;
    private boolean state;
    private Date createTime;
    private Date updateTime;

    public Review() {
    }

    public Review(String id, String owner, String content, boolean deleted, String eventId, boolean state,
                  Date createTime) {
        this.id = id;
        this.owner = owner;
        this.content = content;
        this.deleted = deleted;
        this.eventId = eventId;
        this.state = state;
        this.createTime = createTime;
    }

    public Review(String id, String owner, String content, boolean deleted, String eventId, boolean state,
                  Date createTime, Date updateTime) {
        this.id = id;
        this.owner = owner;
        this.content = content;
        this.deleted = deleted;
        this.eventId = eventId;
        this.state = state;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false, length = 50)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "owner", nullable = false, length = 50)
    public String getOwner() {
        return this.owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    @Column(name = "content", nullable = false)
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Column(name = "deleted", nullable = false)
    public boolean isDeleted() {
        return this.deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    @Column(name = "event_id", nullable = false, length = 50)
    public String getEventId() {
        return this.eventId;
    }

    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    @Column(name = "state", nullable = false)
    public boolean isState() {
        return this.state;
    }

    public void setState(boolean state) {
        this.state = state;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", nullable = false, length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
