debug: false
http:
    mappers:
        jsonPrettyPrint: true

logging:
    level:
        org:
            hibernate: WARN
            springframework:
                web: WARN
        root: INFO

server:
    port: ${PORT:8080}

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 1
        max-active: 8
        max-wait: 30000
        maxIdle: 2
        minIdle: 1
        minEvictableIdleTimeMillis: 120000
        removeAbandoned: true
        test-on-borrow: true
        testOnConnect: true
        timeBetweenEvictionRunsMillis: 30000
        validationQuery: SELECT 1
        url: ${DATABASE_URL:jdbc:mysql://localhost/bookapp?autoReconnect=true&useSSL=false}
        username: ${DATABASE_USERNAME:bookapp}
        password: ${DATABASE_PASSWORD:bookapp}
    jackson:
        serialization:
            indent_output: true
