debug: false
http:
    mappers:
        jsonPrettyPrint: true

logging:
    level:
        org:
            hibernate: WARN
            springframework:
                web: WARN
        root: WARN

mybatis:
    config: classpath:/config/mybatis-config.xml

root_photo_path: /var/www/ezgo/uploads

server:
    port: ${port:8080}

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 1
        max-active: 8
        max-wait: 30000
        maxIdle: 2
        minEvictableIdleTimeMillis: 120000
        minIdle: 1
        password: ${DATABASE_PASSWORD:root}
        removeAbandoned: true
        test-on-borrow: true
        testOnConnect: true
        timeBetweenEvictionRunsMillis: 30000
        url: ${DATABASE_URL:jdbc:mysql://localhost/ezgo?autoReconnect=true&useSSL=false}
        username: ${DATABASE_USERNAME:root}
        validationQuery: SELECT 1
    jackson:
        serialization:
            indent_output: true
