package com.ezgo.domain;
// Generated Dec 27, 2016 4:46:31 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Likes generated by hbm2java
 */
@Entity
@Table(name = "likes", catalog = "ezgo")
public class Likes implements java.io.Serializable {

    private LikesId id;

    public Likes() {
    }

    public Likes(LikesId id) {
        this.id = id;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false, length = 50)),
            @AttributeOverride(name = "eventId", column = @Column(name = "event_id", nullable = false, length = 50)),
            @AttributeOverride(name = "type", column = @Column(name = "type", nullable = false)),
            @AttributeOverride(name = "createTime", column = @Column(name = " create_time", nullable = false, length = 19))})
    public LikesId getId() {
        return this.id;
    }

    public void setId(LikesId id) {
        this.id = id;
    }

}
