package com.ezgo.domain;
// Generated Dec 27, 2016 4:46:31 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.util.Date;

/**
 * PhotoEvents generated by hbm2java
 */
@Entity
@Table(name = "photo_events", catalog = "ezgo")
public class PhotoEvents implements java.io.Serializable {

    private String id;
    private String eventId;
    private String userName;
    private String extension;
    private String path;
    private Date createTime;
    private Date updateTime;

    public PhotoEvents() {
    }

    public PhotoEvents(String id, String eventId, String userName, String extension, String path, Date createTime) {
        this.id = id;
        this.eventId = eventId;
        this.userName = userName;
        this.extension = extension;
        this.path = path;
        this.createTime = createTime;
    }

    public PhotoEvents(String id, String eventId, String userName, String extension, String path, Date createTime,
                       Date updateTime) {
        this.id = id;
        this.eventId = eventId;
        this.userName = userName;
        this.extension = extension;
        this.path = path;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false, length = 50)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "event_id", nullable = false, length = 50)
    public String getEventId() {
        return this.eventId;
    }

    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    @Column(name = "user_name", nullable = false, length = 50)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Column(name = "extension", nullable = false, length = 20)
    public String getExtension() {
        return this.extension;
    }

    public void setExtension(String extension) {
        this.extension = extension;
    }

    @Column(name = "path", nullable = false)
    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", nullable = false, length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
