package com.ezgo.domain;
// Generated Dec 27, 2016 4:46:31 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Provinces generated by hbm2java
 */
@Entity
@Table(name = "provinces", catalog = "ezgo")
public class Provinces implements java.io.Serializable {

    private String code;
    private String name;
    private String type;

    public Provinces() {
    }

    public Provinces(String code, String name, String type) {
        this.code = code;
        this.name = name;
        this.type = type;
    }

    @Id

    @Column(name = "code", unique = true, nullable = false, length = 5)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "type", nullable = false, length = 30)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
