package com.ezgo.domain;
// Generated Dec 27, 2016 4:46:31 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * UserFacebook generated by hbm2java
 */
@Entity
@Table(name = "user_facebook", catalog = "ezgo")
public class UserFacebook implements java.io.Serializable {

    private Integer id;
    private String username;
    private String accessToken;
    private Date expired;
    private int userId;
    private String password;

    public UserFacebook() {
    }

    public UserFacebook(String username, String accessToken, Date expired, int userId, String password) {
        this.username = username;
        this.accessToken = accessToken;
        this.expired = expired;
        this.userId = userId;
        this.password = password;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "username", nullable = false, length = 50)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "access_token", nullable = false, length = 256)
    public String getAccessToken() {
        return this.accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "expired", nullable = false, length = 19)
    public Date getExpired() {
        return this.expired;
    }

    public void setExpired(Date expired) {
        this.expired = expired;
    }

    @Column(name = "user_id", nullable = false)
    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    @Column(name = "password", nullable = false, length = 256)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
