package com.example.spring.app.domain;
// Generated Dec 27, 2016 4:46:31 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.util.Date;

/**
 * LikesId generated by hbm2java
 */
@Embeddable
public class UserBook implements java.io.Serializable {

    private String userId;
    private String eventId;
    private byte type;
    private Date createTime;

    public UserBook() {
    }

    public UserBook(String userId, String eventId, byte type, Date createTime) {
        this.userId = userId;
        this.eventId = eventId;
        this.type = type;
        this.createTime = createTime;
    }

    @Column(name = "user_id", nullable = false, length = 50)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "event_id", nullable = false, length = 50)
    public String getEventId() {
        return this.eventId;
    }

    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    @Column(name = "type", nullable = false)
    public byte getType() {
        return this.type;
    }

    public void setType(byte type) {
        this.type = type;
    }

    @Column(name = " create_time", nullable = false, length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof UserBook))
            return false;
        UserBook castOther = (UserBook) other;

        return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
                && castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
                && ((this.getEventId() == castOther.getEventId()) || (this.getEventId() != null
                && castOther.getEventId() != null && this.getEventId().equals(castOther.getEventId())))
                && (this.getType() == castOther.getType())
                && ((this.getCreateTime() == castOther.getCreateTime())
                || (this.getCreateTime() != null && castOther.getCreateTime() != null
                && this.getCreateTime().equals(castOther.getCreateTime())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
        result = 37 * result + (getEventId() == null ? 0 : this.getEventId().hashCode());
        result = 37 * result + this.getType();
        result = 37 * result + (getCreateTime() == null ? 0 : this.getCreateTime().hashCode());
        return result;
    }

}
