package com.ezgo.app.domain;
// Generated Dec 27, 2016 4:46:31 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.util.Date;

/**
 * Events generated by hbm2java
 */
@Entity
@Table(name = "events", catalog = "ezgo")
public class Book implements java.io.Serializable {

    private String id;
    private String name;
    private String description;
    private String province;
    private Double latitude;
    private Double longitude;
    private String address;
    private Date timeStart;
    private Date timeEnd;
    private String owner;
    private Integer categoryId;
    private boolean state;
    private boolean deleted;
    private Date createTime;
    private Date updateTime;

    public Book() {
    }

    public Book(String id, String name, String province, String address, Date timeStart, String owner, boolean state,
                boolean deleted, Date createTime) {
        this.id = id;
        this.name = name;
        this.province = province;
        this.address = address;
        this.timeStart = timeStart;
        this.owner = owner;
        this.state = state;
        this.deleted = deleted;
        this.createTime = createTime;
    }

    public Book(String id, String name, String description, String province, Double latitude, Double longitude,
                String address, Date timeStart, Date timeEnd, String owner, Integer categoryId, boolean state,
                boolean deleted, Date createTime, Date updateTime) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.province = province;
        this.latitude = latitude;
        this.longitude = longitude;
        this.address = address;
        this.timeStart = timeStart;
        this.timeEnd = timeEnd;
        this.owner = owner;
        this.categoryId = categoryId;
        this.state = state;
        this.deleted = deleted;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false, length = 50)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "province", nullable = false, length = 5)
    public String getProvince() {
        return this.province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    @Column(name = "latitude", precision = 11, scale = 0)
    public Double getLatitude() {
        return this.latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    @Column(name = "longitude", precision = 11, scale = 0)
    public Double getLongitude() {
        return this.longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    @Column(name = "address", nullable = false)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "time_start", nullable = false, length = 19)
    public Date getTimeStart() {
        return this.timeStart;
    }

    public void setTimeStart(Date timeStart) {
        this.timeStart = timeStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "time_end", length = 19)
    public Date getTimeEnd() {
        return this.timeEnd;
    }

    public void setTimeEnd(Date timeEnd) {
        this.timeEnd = timeEnd;
    }

    @Column(name = "owner", nullable = false, length = 50)
    public String getOwner() {
        return this.owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    @Column(name = "category_id")
    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    @Column(name = "state", nullable = false)
    public boolean isState() {
        return this.state;
    }

    public void setState(boolean state) {
        this.state = state;
    }

    @Column(name = "deleted", nullable = false)
    public boolean isDeleted() {
        return this.deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", nullable = false, length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
